version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hms_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hms_password
      POSTGRES_DB: hms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: hms_mailpit
    restart: always
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP Port

volumes:
  postgres_data:
